title: Creative Coding OER
#logo: /assets/OER_Logo_Open_Educational_Resources.png
description: This is a description of the Creative Coding Open Educational Resource
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
